// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnvyrnwknnnecnkgmuhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_j6R-G8IshMcqzr1h3FMHmA_sXyfWrJp"

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error("Missing Supabase environment variables! Check your .env file or deployment settings.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || "", SUPABASE_PUBLISHABLE_KEY || "", {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});